import { PrismaClient, Role, MenuItemStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // =========================
  // CLEAN UP
  // =========================
  console.log("🗑️  Cleaning old data...");
  try {
    await prisma.payment.deleteMany();
    await prisma.orderItemModifier.deleteMany();
    await prisma.orderItem.deleteMany();
    await prisma.order.deleteMany();
    await prisma.tableSession.deleteMany();
    await prisma.review.deleteMany();
    await prisma.menuItemPhoto.deleteMany();
    await prisma.modifierOption.deleteMany();
    await prisma.modifierGroup.deleteMany();
    await prisma.menuItem.deleteMany();
    await prisma.category.deleteMany();
    await prisma.table.deleteMany();
    await prisma.restaurant.deleteMany();
    // Keep Admin to avoid re-login issues if possible, but for "lot of data" request, fresh start is safer for IDs
    // converting to "delete ALL relevant users except maybe admin" is complex. 
    // Let's delete all users to be clean and re-create them.
    await prisma.user.deleteMany(); 
    
    console.log("✅ Old data cleaned!");
  } catch (error) {
    console.log("⚠️  Cleanup had issues (tables might not exist), continuing...");
  }

  const passwordHash = await bcrypt.hash("123456", 10);

  // =========================
  // RESTAURANT
  // =========================
  const restaurant = await prisma.restaurant.create({
    data: {
      name: "Smart Restaurant",
      address: "123 Seed Data Street, HCM",
    },
  });
  console.log("🏠 Restaurant created");

  // =========================
  // CORE USERS
  // =========================
  const roles = [
    { email: "admin@restaurant.com", name: "Super Admin", role: Role.SUPER_ADMIN },
    { email: "kitchen@restaurant.com", name: "Chef Gordon", role: Role.KITCHEN },
    { email: "waiter@restaurant.com", name: "John Waiter", role: Role.WAITER },
  ];

  for (const u of roles) {
    await prisma.user.create({
      data: {
        email: u.email,
        password: passwordHash,
        fullName: u.name,
        role: u.role,
        isVerified: true,
        isActive: true,
      },
    });
  }
  console.log("👤 Core users created");

  // =========================
  // SEED CUSTOMERS (50)
  // =========================
  const customerData = [];
  for (let i = 1; i <= 50; i++) {
    customerData.push({
      email: `customer${i}@example.com`,
      password: passwordHash,
      fullName: `Customer ${i} VIP`,
      role: Role.CUSTOMER,
      isVerified: true,
      isActive: true,
    });
  }
  await prisma.user.createMany({ data: customerData });
  console.log("👥 50 Customers created");

  // =========================
  // SEED STAFF (10)
  // =========================
  const staffData = [];
  for (let i = 1; i <= 5; i++) {
    staffData.push({
      email: `waiter${i}@restaurant.com`,
      password: passwordHash,
      fullName: `Waiter ${i}`,
      role: Role.WAITER,
      isVerified: true,
      isActive: true,
    });
    staffData.push({
      email: `kitchen${i}@restaurant.com`,
      password: passwordHash,
      fullName: `Chef ${i}`,
      role: Role.KITCHEN,
      isVerified: true,
      isActive: true,
    });
  }
  await prisma.user.createMany({ data: staffData });
  console.log("👨‍� 10 Extra Staff created");

  // =========================
  // TABLES (20)
  // =========================
  const tables = [];
  for (let i = 1; i <= 20; i++) {
    tables.push({
      name: `Table ${i}`,
      capacity: i % 4 === 0 ? 8 : 4,
      restaurantId: restaurant.id,
      isActive: true,
       // generate QR url or let backend handle it? 
       // For seed, let's leave qrCodeUrl null or mock it if needed. 
       // Model usually has default or generated by service. 
       // Assuming table creation logic in service handles QR, but here is raw prisma.
       // We'll leave it simple.
    });
  }
  await prisma.table.createMany({ data: tables });
  console.log("🪑 20 Tables created");

  // =========================
  // CATEGORIES & MENU ITEMS
  // =========================
  const categories = ["Appetizers", "Main Course", "Pizza", "Dessert", "Drinks"];
  const createdCats = [];
  
  for (const name of categories) {
    const cat = await prisma.category.create({
        data: { name, restaurantId: restaurant.id }
    });
    createdCats.push(cat);
  }

  // 10 items per category -> 50 items
  for (const cat of createdCats) {
    for (let i = 1; i <= 10; i++) {
        const item = await prisma.menuItem.create({
            data: {
                name: `${cat.name} Item ${i}`,
                description: `Delicious ${cat.name} item number ${i} with special ingredients.`,
                price: 50000 + (i * 10000),
                categoryId: cat.id,
                status: MenuItemStatus.AVAILABLE,
                isChefRecommended: i % 3 === 0,
                photos: {
                    create: {
                        url: `https://source.unsplash.com/random/800x600/?${cat.name.toLowerCase()}`,
                        isPrimary: true
                    }
                }
            }
        });

        // Add Modifiers to some items
        if (i % 2 === 0) {
            await prisma.modifierGroup.create({
                data: {
                    name: "Options",
                    required: false,
                    menuItemId: item.id,
                    options: {
                        create: [
                            { name: "Extra Cheese", priceDelta: 10000 },
                            { name: "No Onion", priceDelta: 0 },
                            { name: "Spicy", priceDelta: 0 }
                        ]
                    }
                }
            });
        }
    }
  }
  console.log("🍔 50 Menu Items created");

  console.log("✅ MASSIVE SEED COMPLETED!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
